# Generated by Django 4.1 on 2022-09-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='картинка'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_number',
            field=models.IntegerField(null=True, verbose_name='номер картинки'),
        ),
    ]
