# Generated by Django 4.0.5 on 2022-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_place_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['place', 'image', 'image_number']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title', 'description_short', 'description_long', 'lng', 'lat', 'place_id']},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='номер картинки'),
        ),
    ]
