# Generated by Django 4.0.5 on 2022-09-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_place_lat_alter_place_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title', 'description_short', 'description_long', 'lng', 'lat']},
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
