# Generated by Django 4.0.5 on 2022-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_place_options_remove_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='картинка'),
        ),
    ]
